
builds:

- id: reposure
  main: ./reposure
  binary: reposure
  goarch:
  - amd64
  goos:
  - linux
  - darwin
  - windows
  ldflags:
  - -X 'github.com/tliron/kutil/version.GitVersion={{.Env.VERSION}}'
  - -X 'github.com/tliron/kutil/version.GitRevision={{.Env.REVISION}}'
  - -X 'github.com/tliron/kutil/version.Timestamp={{.Env.TIMESTAMP}}'

nfpms:

- formats:
  - rpm
  - deb
  homepage: https://github.com/tliron/reposure
  maintainer: Tal Liron <tal.liron@gmail.com>
  description: Manage and access cloud-native container image registries for Kubernetes.
  license: Apache 2.0

archives:

- files:
  - README.md
  - LICENSE
  - NOTICE

  format_overrides:
  - goos: windows
    format: zip

checksum:

  name_template: checksums.txt

release:

  #disable: true
  #prerelease: true

  github:
    owner: tliron
    name: reposure
