// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RegistryListerExpansion allows custom methods to be added to
// RegistryLister.
type RegistryListerExpansion interface{}

// RegistryNamespaceListerExpansion allows custom methods to be added to
// RegistryNamespaceLister.
type RegistryNamespaceListerExpansion interface{}
