// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegistryDirectApplyConfiguration represents an declarative configuration of the RegistryDirect type for use
// with apply.
type RegistryDirectApplyConfiguration struct {
	Host *string `json:"host,omitempty"`
}

// RegistryDirectApplyConfiguration constructs an declarative configuration of the RegistryDirect type for use with
// apply.
func RegistryDirect() *RegistryDirectApplyConfiguration {
	return &RegistryDirectApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *RegistryDirectApplyConfiguration) WithHost(value string) *RegistryDirectApplyConfiguration {
	b.Host = &value
	return b
}
