// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegistryIndirectApplyConfiguration represents an declarative configuration of the RegistryIndirect type for use
// with apply.
type RegistryIndirectApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Service   *string `json:"service,omitempty"`
	Port      *uint64 `json:"port,omitempty"`
}

// RegistryIndirectApplyConfiguration constructs an declarative configuration of the RegistryIndirect type for use with
// apply.
func RegistryIndirect() *RegistryIndirectApplyConfiguration {
	return &RegistryIndirectApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *RegistryIndirectApplyConfiguration) WithNamespace(value string) *RegistryIndirectApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *RegistryIndirectApplyConfiguration) WithService(value string) *RegistryIndirectApplyConfiguration {
	b.Service = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *RegistryIndirectApplyConfiguration) WithPort(value uint64) *RegistryIndirectApplyConfiguration {
	b.Port = &value
	return b
}
