// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegistryStatusApplyConfiguration represents an declarative configuration of the RegistryStatus type for use
// with apply.
type RegistryStatusApplyConfiguration struct {
	SurrogatePod *string `json:"surrogatePod,omitempty"`
}

// RegistryStatusApplyConfiguration constructs an declarative configuration of the RegistryStatus type for use with
// apply.
func RegistryStatus() *RegistryStatusApplyConfiguration {
	return &RegistryStatusApplyConfiguration{}
}

// WithSurrogatePod sets the SurrogatePod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SurrogatePod field is set to the value of the last call.
func (b *RegistryStatusApplyConfiguration) WithSurrogatePod(value string) *RegistryStatusApplyConfiguration {
	b.SurrogatePod = &value
	return b
}
